[package]
name = "traces"
version = "0.1.0"
edition = "2024"

[lib]
name = "traces"
path = "src/lib.rs"

[[bin]]
name = "traces"
path = "src/main.rs"

[dependencies]
serde = "1.0.228"
serde_json = "1.0.145"
