[package]
name = "explor-auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
actix-cors = "0.7.1"
